name: Build Common Problems Document

on:
  # push:
  #   paths:
  #     - 'docs/*'
  # pull_request:
  #   paths:
  #     - 'docs/*'
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Compile TeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: problems.tex
        working_directory: docs/
        args: -xelatex -file-line-error -interaction=nonstopmode -shell-escape
        extra_system_packages: "msttcorefonts-installer fontconfig"
        pre_compile: "update-ms-fonts && fc-cache -f && bash fonts/install.sh && fc-list"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: CommonProblems.pdf
        path: docs/main.pdf
