# This is a basic workflow to help you get started with Actions

name: Build videos

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: 
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: "contains(github.event.head_commit.message, '[render]')"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Render videos
      uses: manim-kindergarten/manim_action_renderer@dev
      id: renderer
      with:
        source_file: videos/manimTutorial/part6_Miscellaneous.py
        scene_names: "TracedPathTutorial"
        args: "--ultra_high_quality"
        extra_repos: "https://github.com/Tony031218/manim_projects https://github.com/manim-kindergarten/manim_sandbox"

    # Runs a set of commands using the runners shell
    - name: Save output as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Videos
        path: ${{ steps.renderer.outputs.video_path }}